const HISTORICAL_YEAR_FROM = 1986;
const HISTORICAL_YEAR_TO = 2019;
const PROJECTIONS_YEAR_FROM = 2020;
const PROJECTIONS_YEAR_TO = 2030;

const MIN_YEAR = Math.min(HISTORICAL_YEAR_FROM, PROJECTIONS_YEAR_FROM);
const MAX_YEAR = Math.max(HISTORICAL_YEAR_TO, PROJECTIONS_YEAR_TO);

export default {
  historical: { YEAR_FROM: HISTORICAL_YEAR_FROM, YEAR_TO: HISTORICAL_YEAR_TO },
  projections: {
    YEAR_FROM: PROJECTIONS_YEAR_FROM,
    YEAR_TO: PROJECTIONS_YEAR_TO,
  },
  minMax: { YEAR_FROM: MIN_YEAR, YEAR_TO: MAX_YEAR },
};
